version: '3'                                                                                                                                                             
                                                                                                                                                                         
services:                                                                                                                                                                
                                                                                                                                                                         
  zookeeper:                                                                                                                                                             
    container_name: zookeeper                                                                                                                                            
    build: zookeeper/                                                                                                                                                    
    ports:                                                                                                                                                               
      - 2185:2185                                                                                                                                                        
    volumes:                                                                                                                                                             
      - ./zookeeper/conf:/opt/zookeeper/conf                                                                                                                             
      - ./zookeeper/data:/tmp/zookeeper                                                                                                                                  
                                                                                                                                                                         
  kafka:                                                                                                                                                                 
    container_name: kafka                                                                                                                                                
    build: kafka/                                                                                                                                                        
                                                                                                                                                                         
    depends_on:                                                                                                                                                          
      - zookeeper                                                                                                                                                        
                                                                                                                                                                         
    ports:                                                                                                                                                               
      - 9092:9092                                                                                                                                                        
    volumes:                                                                                                                                                             
      - ./kafka/conf:/opt/kafka/config                                                                                                                                   
      - ./kafka/data:/tmp/kafka-logs   
  producer-api-changes:
    container_name: producer-api-changes
    build: producer-api-changes/
    depends_on:
      - kafka
    ports:
      - 15000:15000
    environment:
      - HTTP_PORT=15000
      - HTTP_CHECK_INPUT=1
      - KAFKA_HOST=kafka
      - KAFKA_PORT=9092
      - KAFKA_TOPIC=changes
  producer-api-tocrm:
    container_name: producer-api-tocrm
    build: producer-api-changes/
    depends_on:
      - kafka
    ports:
      - 16000:15000
    environment:
      - HTTP_PORT=15000
      - HTTP_CHECK_INPUT=0
      - KAFKA_HOST=kafka
      - KAFKA_PORT=9092
      - KAFKA_TOPIC=tocrm
networks:                                                                                                                                                                
  default:                                                                                                                                                               
    external:                                                                                                                                                            
      name: kafka        